trigger:
- main
strategy:
  matrix:
   linux: 
     operatingSystem: 'ubuntu-latest'
   mac: 
     operatingSystem: 'macos-latest'
pool:
  vmImage: $(operatingSystem)

stages:
- stage: Build
  Jobs: 
  - job: BuildJob
    steps:
    - bash: echo "Do the build"
- stage: DevDeploy
  Jobs: 
  - deployment:DevDeploymentJob
  - environment: Dev
    strataegy:
      runOnce:
        deploy:
          steps:
          - scripts: echo deploy to dev
- stage: QADeploy
  Jobs: 
  - deployment:QADeploymentJob
  - environment: QA
    strataegy:
      runOnce:
        deploy:
          steps:
          - scripts: echo deploy to QA
steps:
- script: echo Runnin on $(operatingSystem)
  displayName: 'Run a one-line script'


